services:
  db:
    image: mysql:8
    container_name: cicd-mysqlDB
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  myapp:
    image: mydockerhub/myapp:latest
    container_name: myapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://cicd-mysqlDB:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
