name: Deploy to Server

on:
  push:
    branches:
      - deploy  # 'deploy' 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root1234
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=5s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Build Docker Image
        run: docker build -t cicdmyapp:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag cicdmyapp:latest eomheeseung/cicdmyapp:latest
          docker push eomhseeseung/cicdmyapp:latest

      - name: Deploy to Docker
        run: |
          docker pull eomheeseung/cicdmyapp:latest
          docker stop cicdmyapp || true
          docker rm cicdmyapp || true
          docker run -d --name cicdmyapp -p 8080:8080 \
            -e SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC \
            -e SPRING_DATASOURCE_USERNAME=root \
            -e SPRING_DATASOURCE_PASSWORD=root1234 \
            eomheeseung/cicdmyapp:latest


      
